[2025-04-16 06:31:38,599: INFO: main: Logging is implemented]
[2025-04-19 11:34:07,901: INFO: main: Logging is implemented]
[2025-04-19 11:36:14,221: INFO: main: Logging is implemented]
[2025-04-19 11:36:29,066: INFO: main: Logging is implemented]
[2025-04-19 11:43:56,108: INFO: main: Logging is implemented]
[2025-04-19 11:45:18,717: INFO: main: Logging is implemented]
[2025-04-19 11:46:27,085: INFO: main: stage Data Ingestion stage initiated]
[2025-04-19 11:46:27,085: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 11:46:27,085: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 11:46:27,085: INFO: common: created directory at: artifacts]
[2025-04-19 11:46:27,085: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-19 11:47:27,031: INFO: data_ingestion: File is downloaded]
[2025-04-19 11:47:27,140: INFO: main: Stage Data Ingestion stage Completed]
[2025-04-20 11:54:28,297: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-20 11:54:28,629: INFO: main: stage Data Ingestion stage initiated]
[2025-04-20 11:54:28,629: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-20 11:54:28,638: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-20 11:54:28,638: INFO: common: created directory at: artifacts]
[2025-04-20 11:54:28,638: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-20 11:54:28,638: INFO: data_ingestion: File already exits]
[2025-04-20 11:54:28,738: INFO: main: Stage Data Ingestion stage Completed]
[2025-04-20 11:54:28,738: INFO: main: stage Data Transformation stage initiated]
[2025-04-20 11:54:28,745: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-20 11:54:28,746: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-20 11:54:28,747: INFO: common: created directory at: artifacts]
[2025-04-20 11:54:28,747: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-20 11:54:35,521: INFO: main: Stage Data Transformation stage Completed]
[2025-04-22 12:33:18,290: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-22 12:33:19,456: INFO: main: stage Data Ingestion stage initiated]
[2025-04-22 12:33:19,456: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-22 12:33:19,456: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-22 12:33:19,456: INFO: common: created directory at: artifacts]
[2025-04-22 12:33:19,456: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-22 12:33:19,456: INFO: data_ingestion: File already exits]
[2025-04-22 12:33:19,556: INFO: main: Stage Data Ingestion stage Completed]
[2025-04-22 12:33:19,556: INFO: main: stage Data Transformation stage initiated]
[2025-04-22 12:33:19,556: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-22 12:33:19,556: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-22 12:33:19,556: INFO: common: created directory at: artifacts]
[2025-04-22 12:33:19,556: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-22 12:33:20,890: INFO: main: Stage Data Transformation stage Completed]
[2025-04-22 12:33:20,890: INFO: main: stage Model Trainer stage initiated]
[2025-04-22 12:33:20,892: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-22 12:33:20,892: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-22 12:33:20,895: INFO: common: created directory at: artifacts]
[2025-04-22 12:33:20,895: ERROR: main: 'ConfigurationManager' object has no attribute 'params']
Traceback (most recent call last):
  File "C:\Projects\TextSummarizer\main.py", line 33, in <module>
    model_trainer_pipeline.initiate_model_trainer()
  File "C:\Projects\TextSummarizer\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "C:\Projects\TextSummarizer\src\textSummarizer\config\configuration.py", line 44, in get_model_trainer_config
    params=self.params.TrainingArguments
AttributeError: 'ConfigurationManager' object has no attribute 'params'
[2025-04-22 12:35:16,665: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-22 12:35:17,724: INFO: main: stage Data Ingestion stage initiated]
[2025-04-22 12:35:17,733: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-22 12:35:17,733: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-22 12:35:17,733: INFO: common: created directory at: artifacts]
[2025-04-22 12:35:17,733: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-22 12:35:17,733: INFO: data_ingestion: File already exits]
[2025-04-22 12:35:17,814: INFO: main: Stage Data Ingestion stage Completed]
[2025-04-22 12:35:17,814: INFO: main: stage Data Transformation stage initiated]
[2025-04-22 12:35:17,814: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-22 12:35:17,830: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-22 12:35:17,830: INFO: common: created directory at: artifacts]
[2025-04-22 12:35:17,830: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-22 12:35:19,067: INFO: main: Stage Data Transformation stage Completed]
[2025-04-22 12:35:19,068: INFO: main: stage Model Trainer stage initiated]
[2025-04-22 12:35:19,070: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-22 12:35:19,072: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-22 12:35:19,072: INFO: common: created directory at: artifacts]
[2025-04-22 12:35:19,073: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-22 12:41:21,331: ERROR: main: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy']
Traceback (most recent call last):
  File "C:\Projects\TextSummarizer\main.py", line 33, in <module>
    model_trainer_pipeline.initiate_model_trainer()
  File "C:\Projects\TextSummarizer\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 12, in initiate_model_trainer
    model_trainer_config.train()
  File "C:\Projects\TextSummarizer\src\textSummarizer\components\model_trainer.py", line 22, in train
    trainer_args = TrainingArguments(
TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy'
[2025-04-22 13:06:28,346: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-22 13:06:29,911: INFO: main: stage Data Ingestion stage initiated]
[2025-04-22 13:06:29,914: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-22 13:06:29,915: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-22 13:06:29,915: INFO: common: created directory at: artifacts]
[2025-04-22 13:06:29,916: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-22 13:06:29,916: INFO: data_ingestion: File already exits]
[2025-04-22 13:06:30,006: INFO: main: Stage Data Ingestion stage Completed]
[2025-04-22 13:06:30,006: INFO: main: stage Data Transformation stage initiated]
[2025-04-22 13:06:30,006: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-22 13:06:30,006: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-22 13:06:30,006: INFO: common: created directory at: artifacts]
[2025-04-22 13:06:30,006: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-22 13:06:31,332: INFO: main: Stage Data Transformation stage Completed]
[2025-04-22 13:06:31,333: INFO: main: stage Model Trainer stage initiated]
[2025-04-22 13:06:31,334: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-22 13:06:31,336: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-22 13:06:31,337: INFO: common: created directory at: artifacts]
[2025-04-22 13:06:31,337: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-22 13:06:38,392: ERROR: main: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy']
Traceback (most recent call last):
  File "C:\Projects\TextSummarizer\main.py", line 33, in <module>
    model_trainer_pipeline.initiate_model_trainer()
  File "C:\Projects\TextSummarizer\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 12, in initiate_model_trainer
    model_trainer_config.train()
  File "C:\Projects\TextSummarizer\src\textSummarizer\components\model_trainer.py", line 22, in train
    trainer_args = TrainingArguments(
TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy'
[2025-04-22 14:46:54,423: INFO: config: PyTorch version 2.6.0 available.]
[2025-04-22 14:46:55,599: INFO: main: stage Data Ingestion stage initiated]
[2025-04-22 14:46:55,614: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-22 14:46:55,614: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-22 14:46:55,614: INFO: common: created directory at: artifacts]
[2025-04-22 14:46:55,614: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-22 14:46:55,614: INFO: data_ingestion: File already exits]
[2025-04-22 14:46:55,698: INFO: main: Stage Data Ingestion stage Completed]
[2025-04-22 14:46:55,698: INFO: main: stage Data Transformation stage initiated]
[2025-04-22 14:46:55,698: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-22 14:46:55,698: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-22 14:46:55,698: INFO: common: created directory at: artifacts]
[2025-04-22 14:46:55,698: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-22 14:46:56,874: INFO: main: Stage Data Transformation stage Completed]
[2025-04-22 14:46:56,874: INFO: main: stage Model Trainer stage initiated]
[2025-04-22 14:46:56,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-22 14:46:56,874: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-22 14:46:56,874: INFO: common: created directory at: artifacts]
[2025-04-22 14:46:56,874: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-22 16:15:14,852: INFO: main: Stage Model Trainer stage Completed]
[2025-05-14 11:52:25,272: INFO: server: Started server process [7120]]
[2025-05-14 11:52:25,272: INFO: on: Waiting for application startup.]
[2025-05-14 11:52:25,272: INFO: on: Application startup complete.]
[2025-05-14 11:52:25,288: INFO: server: Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)]
[2025-05-14 12:00:27,469: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2025-05-14 12:00:27,473: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-05-14 12:00:28,680: INFO: config: PyTorch version 2.6.0 available.]
[2025-05-14 12:00:35,123: INFO: main: stage Data Ingestion stage initiated]
[2025-05-14 12:00:35,131: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-14 12:00:35,136: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-14 12:00:35,139: INFO: common: created directory at: artifacts]
[2025-05-14 12:00:35,140: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-14 12:00:35,141: INFO: data_ingestion: File already exits]
[2025-05-14 12:00:35,476: INFO: main: Stage Data Ingestion stage Completed]
[2025-05-14 12:00:35,476: INFO: main: stage Data Transformation stage initiated]
[2025-05-14 12:00:35,492: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-14 12:00:35,503: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-14 12:00:35,508: INFO: common: created directory at: artifacts]
[2025-05-14 12:00:35,509: INFO: common: created directory at: artifacts/data_transformation]
[2025-05-14 12:00:38,416: INFO: main: Stage Data Transformation stage Completed]
[2025-05-14 12:00:38,416: INFO: main: stage Model Trainer stage initiated]
[2025-05-14 12:00:38,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-14 12:00:38,432: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-14 12:00:38,439: INFO: common: created directory at: artifacts]
[2025-05-14 12:00:38,441: INFO: common: created directory at: artifacts/model_trainer]
[2025-05-14 12:00:38,441: ERROR: main: "'ConfigBox' object has no attribute 'evaluation_strategy'"]
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'evaluation_strategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'evaluation_strategy'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'evaluation_strategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'evaluation_strategy'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'evaluation_strategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'evaluation_strategy'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'evaluation_strategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Projects\TextSummarizer\main.py", line 34, in <module>
    model_trainer_pipeline.initiate_model_trainer()
  File "C:\Projects\TextSummarizer\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\TextSummarizer\src\textSummarizer\config\configuration.py", line 57, in get_model_trainer_config
    evaluation_strategy = params.evaluation_strategy,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'evaluation_strategy'"
[2025-05-14 12:01:40,385: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-14 12:01:40,385: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-14 12:01:40,385: INFO: common: created directory at: artifacts]
[2025-05-14 12:01:40,385: INFO: common: created directory at: artifacts/model_evaluation]
[2025-05-14 12:56:44,785: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-14 12:56:44,785: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-14 12:56:44,785: INFO: common: created directory at: artifacts]
[2025-05-14 12:56:44,785: INFO: common: created directory at: artifacts/model_evaluation]
[2025-05-14 12:59:46,684: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-14 12:59:46,688: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-14 12:59:46,689: INFO: common: created directory at: artifacts]
[2025-05-14 12:59:46,690: INFO: common: created directory at: artifacts/model_evaluation]
[2025-05-14 14:21:18,410: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-14 14:21:18,414: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-14 14:21:18,416: INFO: common: created directory at: artifacts]
[2025-05-14 14:21:18,417: INFO: common: created directory at: artifacts/model_evaluation]
